// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlqflwbnluqpgeaunugb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5scWZsd2JubHVxcGdlYXVudWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODIyODksImV4cCI6MjA2NDI1ODI4OX0.ISqwj9ZZTBe6ZQm0uJu8zn_IGvGYxqPtFeXdlJVdtZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);